---
title: "Image-Processing-With-R"
author: "Adarsh Pawar"
date: "27/08/2019"
output: pdf_document
---
## Load Packages
```{r setup, include=FALSE}
#install.packages("BiocManager") 
#BiocManager::install("EBImage")
library(EBImage)
#install_keras()
library(keras)
#keras is a high level neural network API for deep learning from TenserFlow Google. 
#devtools::install_github("rstudio/keras")
library(tensorflow)
#install_tensorflow(package_url = "https://pypi.python.org/packages/b8/d6/af3d52dd52150ec4a6ceb7788bfeb2f62ecb6aa2d1172211c4db39b349a2/tensorflow-1.3.0rc0-cp27-cp27mu-manylinux1_x86_64.whl#md5=1cf77a2360ae2e38dd3578618eacc03b")

```

##  Read images

```{r}

readImage("Image/HD1.jpg")
pics <- c('Image/HD1.jpg', 'Image/HD2.jpg', 'Image/HD3.jpg', 'Image/HD4.jpg', 'Image/HD5.jpg', 'Image/HD6.jpg', 'Image/HD7.jpg', 'Image/HD8.jpg', 'Image/HD9.jpg', 'Image/P1.jpg', 'Image/P2.jpg', 'Image/P3.jpg', 'Image/P4.jpg', 'Image/P5.jpg', 'Image/P6.jpg', 'Image/P7.jpg', 'Image/P8.jpg', 'Image/P9.jpg')
testPics <- c("TestImage/HDTest.jpg","TestImage/PTest.jpg")
myPic <- list()
myTestPic <- list()
for (i in 1:18) 
{
  myPic[[i]] <- readImage(pics[i])
}
for (i in 1:2) 
{
  myTestPic[[i]] <- readImage(testPics[i])
}
print(readImage(pics[3]))

```


## Explore
```{r pressure}
print(myPic[[1]])
display(myPic[[8]])
summary(myPic[[1]])
hist(myPic[[2]])
str(myPic)
```

## Resize
```{r pressure, echo=FALSE}
for (i in 1:18) 
{
  myPic[[i]] <- resize(myPic[[i]], 225, 225)
}
for (i in 1:2) 
{
  myTestPic[[i]] <- resize(myTestPic[[i]], 225, 225)
}
str(myPic)
```

## Reshape
```{r pressure, echo=FALSE}
for (i in 1:18) 
{
  myPic[[i]] <- array_reshape(myPic[[i]], c(225, 225, 3))
}
for (i in 1:2) 
{
  myTestPic[[i]] <- array_reshape(myTestPic[[i]], c(225, 225, 3))
}
str(myTestPic)
```

## Row Binding for training and testing
```{r pressure, echo=FALSE}
trainx <- NULL
for (i in 1:18) 
{
  trainx <- rbind(trainx, myPic[[i]]) 
}
str(trainx)
testx <- rbind(myTestPic[[1]], myTestPic[[2]])
trainy <- c(0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1)
testy <- c(0,1)

```
## On Hot Encoding
```{r pressure, echo=FALSE}
trainLables <- to_categorical(trainy)
trainLables
testLables <- to_categorical(testy)
testLables
```

## Model

```{r pressure, echo=FALSE}
model <- keras_model_sequential()
model %>%
  layer_dense(units = 256, activation = 'relu', input_shape = c(151875)) %>%
  layer_dense(units = 128, activation = 'relu') %>%
  layer_dense(units = 2, activation = 'softmax')
summary(model)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
